"""initial_schema

Revision ID: 948f96f945f0
Revises: 
Create Date: 2026-05-28 16:34:47.231619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # noqa: F401 — registers Vector type

# revision identifiers, used by Alembic.
revision: str = '948f96f945f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_storage_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('brands',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_storage_key', sa.String(length=1000), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_dna', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('PODCAST', 'TUTORIAL', 'VLOG', 'SHORTS', 'INTERVIEW', 'OTHER', name='content_type_enum'), nullable=False),
    sa.Column('editor_mode', sa.Enum('PODCAST', 'SHORTS', 'VISUAL_CREATOR', 'FULL_EDITOR', 'TUTORIAL', 'QUICK_EXPORT', name='editor_mode_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'READY', 'ERROR', name='project_status_enum'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('media_type', sa.Enum('VIDEO', 'AUDIO', name='media_type_enum'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'UPLOADED', 'TRANSCRIBING', 'ANALYZING', 'READY', 'ERROR', name='asset_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('media_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_transcription_task_id', sa.String(length=255), nullable=True),
    sa.Column('celery_analysis_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_project_id'), 'embeddings', ['project_id'], unique=False)
    op.create_table('timelines',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['timelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_is_active'), 'timelines', ['is_active'], unique=False)
    op.create_index(op.f('ix_timelines_project_id'), 'timelines', ['project_id'], unique=False)
    op.create_table('costs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costs_project_id'), 'costs', ['project_id'], unique=False)
    op.create_table('renders',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'YOUTUBE_SHORTS', 'INSTAGRAM', 'INSTAGRAM_REELS', 'TIKTOK', 'FACEBOOK', 'CUSTOM', name='render_platform_enum'), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'ERROR', 'CANCELLED', name='render_status_enum'), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('render_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_project_id'), 'renders', ['project_id'], unique=False)
    op.create_index(op.f('ix_renders_status'), 'renders', ['status'], unique=False)
    op.create_index(op.f('ix_renders_timeline_id'), 'renders', ['timeline_id'], unique=False)
    op.create_table('scenes',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('energy_level', sa.Float(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=False),
    sa.Column('highlight_score', sa.Float(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('platform_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_asset_id'), 'scenes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scenes_is_highlight'), 'scenes', ['is_highlight'], unique=False)
    op.create_table('suggestions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('HOOK_REWRITE', 'CUT', 'TRANSITION', 'CAPTION', 'HIGHLIGHT', 'SHORT_CLIP', 'REMOVE_FILLER', 'REORDER', 'AUDIO_FIX', 'VISUAL_OPPORTUNITY', name='suggestion_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'APPLIED', 'MODIFIED', name='suggestion_status_enum'), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_asset_id'), 'suggestions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_suggestions_project_id'), 'suggestions', ['project_id'], unique=False)
    op.create_index(op.f('ix_suggestions_status'), 'suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_suggestions_type'), 'suggestions', ['type'], unique=False)
    op.create_table('transcripts',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filler_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'ERROR', name='transcript_status_enum'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_asset_id'), 'transcripts', ['asset_id'], unique=True)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('shorts',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('why_viral', sa.Text(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('platform_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'APPROVED', 'REJECTED', 'RENDERING', 'RENDERED', name='short_status_enum'), nullable=False),
    sa.Column('render_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shorts_asset_id'), 'shorts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_shorts_project_id'), 'shorts', ['project_id'], unique=False)
    op.create_index(op.f('ix_shorts_status'), 'shorts', ['status'], unique=False)

    # ── Specialised indexes (T-0.3.3) ─────────────────────────────────────────

    # pgvector HNSW index on embeddings — fast approximate nearest-neighbour search
    # Using cosine distance (most appropriate for text embeddings)
    op.execute(
        "CREATE INDEX ix_embeddings_embedding_hnsw "
        "ON embeddings USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )

    # pg_trgm GIN index on transcript full_text for Nepali text search
    # pg_trgm works with Unicode / Devanagari script
    op.execute(
        "CREATE INDEX ix_transcripts_full_text_trgm "
        "ON transcripts USING gin (full_text gin_trgm_ops)"
    )

    # Composite index: project cost queries (sum costs per project)
    op.create_index(
        "ix_costs_project_task",
        "costs",
        ["project_id", "task"],
        unique=False,
    )

    # Composite index: scenes ordered by asset + time (timeline rendering)
    op.create_index(
        "ix_scenes_asset_time",
        "scenes",
        ["asset_id", "start_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorts_status'), table_name='shorts')
    op.drop_index(op.f('ix_shorts_project_id'), table_name='shorts')
    op.drop_index(op.f('ix_shorts_asset_id'), table_name='shorts')
    op.drop_table('shorts')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_asset_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_suggestions_type'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_status'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_project_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_asset_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_scenes_is_highlight'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_asset_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_renders_timeline_id'), table_name='renders')
    op.drop_index(op.f('ix_renders_status'), table_name='renders')
    op.drop_index(op.f('ix_renders_project_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_costs_project_id'), table_name='costs')
    op.drop_table('costs')
    op.drop_index(op.f('ix_timelines_project_id'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_is_active'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('ix_embeddings_project_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Drop specialised indexes
    op.execute("DROP INDEX IF EXISTS ix_scenes_asset_time")
    op.execute("DROP INDEX IF EXISTS ix_costs_project_task")
    op.execute("DROP INDEX IF EXISTS ix_transcripts_full_text_trgm")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_embedding_hnsw")

    # Drop enum types
    sa.Enum(name='short_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='suggestion_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='suggestion_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transcript_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='render_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='render_platform_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='media_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='project_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='editor_mode_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
